<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('cities')->delete();
        $cities = array(
            array('name' => "Aba", 'state_id' => 1),
            array('name' => "Amaigbo", 'state_id' => 1),
            array('name' => "Arochukwu", 'state_id' => 1),
            array('name' => "Bende", 'state_id' => 1),
            array('name' => "Ohafia", 'state_id' => 1),
            array('name' => "Okwe", 'state_id' => 1),
            array('name' => "Umuahia", 'state_id' => 1),
            array('name' => "Demsa", 'state_id' => 3),
            array('name' => "Ganye", 'state_id' => 3),
            array('name' => "Girei", 'state_id' => 3),
            array('name' => "Gombi", 'state_id' => 3),
            array('name' => "Jada", 'state_id' => 3),
            array('name' => "Jimeta", 'state_id' => 3),
            array('name' => "Lamurde", 'state_id' => 3),
            array('name' => "Madagala", 'state_id' => 3),
            array('name' => "Maiha", 'state_id' => 3),
            array('name' => "Mubi", 'state_id' => 3),
            array('name' => "Ngurore", 'state_id' => 3),
            array('name' => "Numan", 'state_id' => 3),
            array('name' => "Shelleng", 'state_id' => 3),
            array('name' => "Song", 'state_id' => 3),
            array('name' => "Toungo", 'state_id' => 3),
            array('name' => "Yola", 'state_id' => 3),
            array('name' => "Aguata", 'state_id' => 5),
            array('name' => "Agulu", 'state_id' => 5),
            array('name' => "Anambra", 'state_id' => 5),
            array('name' => "Awka", 'state_id' => 5),
            array('name' => "Enugu Ukwu", 'state_id' => 5),
            array('name' => "Igbo Ukwu", 'state_id' => 5),
            array('name' => "Ihiala", 'state_id' => 5),
            array('name' => "Nkpor", 'state_id' => 5),
            array('name' => "Nnewi", 'state_id' => 5),
            array('name' => "Obosi", 'state_id' => 5),
            array('name' => "Okija", 'state_id' => 5),
            array('name' => "Okpoko", 'state_id' => 5),
            array('name' => "Onitsha", 'state_id' => 5),
            array('name' => "Ozubulu", 'state_id' => 5),
            array('name' => "Uga", 'state_id' => 5),
            array('name' => "Alkaleri", 'state_id' => 6),
            array('name' => "Azare", 'state_id' => 6),
            array('name' => "Bauchi", 'state_id' => 6),
            array('name' => "Bogoro", 'state_id' => 6),
            array('name' => "Bununu Dass", 'state_id' => 6),
            array('name' => "Darazo", 'state_id' => 6),
            array('name' => "Gamawa", 'state_id' => 6),
            array('name' => "Ganjuwa", 'state_id' => 6),
            array('name' => "Jamari", 'state_id' => 6),
            array('name' => "Katagum", 'state_id' => 6),
            array('name' => "Misau", 'state_id' => 6),
            array('name' => "Ningi", 'state_id' => 6),
            array('name' => "Tafawa Balewa", 'state_id' => 6),
            array('name' => "Brass", 'state_id' => 7),
            array('name' => "Ekeremor", 'state_id' => 7),
            array('name' => "Nembe", 'state_id' => 7),
            array('name' => "Yenagoa", 'state_id' => 7),
            array('name' => "Aliade", 'state_id' => 8),
            array('name' => "Gboko", 'state_id' => 8),
            array('name' => "Katsina-Ala", 'state_id' => 8),
            array('name' => "Makurdi", 'state_id' => 8),
            array('name' => "Otukpo", 'state_id' => 8),
            array('name' => "Ukum", 'state_id' => 8),
            array('name' => "Zaki Biam", 'state_id' => 8),
            array('name' => "Abadan", 'state_id' => 9),
            array('name' => "Askira", 'state_id' => 9),
            array('name' => "Bama", 'state_id' => 9),
            array('name' => "Biu", 'state_id' => 9),
            array('name' => "Chibok", 'state_id' => 9),
            array('name' => "Damboa", 'state_id' => 9),
            array('name' => "Dikwa", 'state_id' => 9),
            array('name' => "Gamboru", 'state_id' => 9),
            array('name' => "Gubio", 'state_id' => 9),
            array('name' => "Gwoza", 'state_id' => 9),
            array('name' => "Kaga", 'state_id' => 9),
            array('name' => "Kala", 'state_id' => 9),
            array('name' => "Konduga", 'state_id' => 9),
            array('name' => "Kukawa", 'state_id' => 9),
            array('name' => "Mafa", 'state_id' => 9),
            array('name' => "Magumeri", 'state_id' => 9),
            array('name' => "Maiduguri", 'state_id' => 9),
            array('name' => "Marte", 'state_id' => 9),
            array('name' => "Monguno", 'state_id' => 9),
            array('name' => "Ngala", 'state_id' => 9),
            array('name' => "Shani", 'state_id' => 9),
            array('name' => "Agbor", 'state_id' => 11),
            array('name' => "Asaba", 'state_id' => 11),
            array('name' => "Bomadi", 'state_id' => 11),
            array('name' => "Burutu", 'state_id' => 11),
            array('name' => "Okpe", 'state_id' => 11),
            array('name' => "Patani", 'state_id' => 11),
            array('name' => "Sapele", 'state_id' => 11),
            array('name' => "Ughelli", 'state_id' => 11),
            array('name' => "Warri", 'state_id' => 11),
            array('name' => "Abakaliki", 'state_id' => 12),
            array('name' => "Afikpo", 'state_id' => 12),
            array('name' => "Effium", 'state_id' => 12),
            array('name' => "Ezza", 'state_id' => 12),
            array('name' => "Ishieke", 'state_id' => 12),
            array('name' => "Uburu", 'state_id' => 12),
            array('name' => "Auchi", 'state_id' => 13),
            array('name' => "Benin", 'state_id' => 13),
            array('name' => "Ekpoma", 'state_id' => 13),
            array('name' => "Igarra", 'state_id' => 13),
            array('name' => "Ikpoba", 'state_id' => 13),
            array('name' => "Irrua", 'state_id' => 13),
            array('name' => "Sabongida", 'state_id' => 13),
            array('name' => "Ubiaja", 'state_id' => 13),
            array('name' => "Uromi", 'state_id' => 13),
            array('name' => "Ado", 'state_id' => 14),
            array('name' => "Aramoko", 'state_id' => 14),
            array('name' => "Efon Alaye", 'state_id' => 14),
            array('name' => "Emure", 'state_id' => 14),
            array('name' => "Igbara Odo", 'state_id' => 14),
            array('name' => "Igede", 'state_id' => 14),
            array('name' => "Ijero", 'state_id' => 14),
            array('name' => "Ikere", 'state_id' => 14),
            array('name' => "Ikole", 'state_id' => 14),
            array('name' => "Ilawe", 'state_id' => 14),
            array('name' => "Ipoti", 'state_id' => 14),
            array('name' => "Ise", 'state_id' => 14),
            array('name' => "Ode", 'state_id' => 14),
            array('name' => "Omuo", 'state_id' => 14),
            array('name' => "Osi", 'state_id' => 14),
            array('name' => "Agwa", 'state_id' => 15),
            array('name' => "Aku", 'state_id' => 15),
            array('name' => "Awgu", 'state_id' => 15),
            array('name' => "Eha Amufu", 'state_id' => 15),
            array('name' => "Enugu", 'state_id' => 15),
            array('name' => "Enugu Ezike", 'state_id' => 15),
            array('name' => "Enugu Ngwo", 'state_id' => 15),
            array('name' => "Ezeagu", 'state_id' => 15),
            array('name' => "Mberubu", 'state_id' => 15),
            array('name' => "Nsukka", 'state_id' => 15),
            array('name' => "Oji", 'state_id' => 15),
            array('name' => "Udi", 'state_id' => 15),
            array('name' => "Ako", 'state_id' => 16),
            array('name' => "Deba", 'state_id' => 16),
            array('name' => "Duku", 'state_id' => 16),
            array('name' => "Garko", 'state_id' => 16),
            array('name' => "Gombe", 'state_id' => 16),
            array('name' => "Kaltungo", 'state_id' => 16),
            array('name' => "Kumo", 'state_id' => 16),
            array('name' => "Nafada", 'state_id' => 16),
            array('name' => "Pindiga", 'state_id' => 16),
            array('name' => "Aboh", 'state_id' => 17),
            array('name' => "Etiti", 'state_id' => 17),
            array('name' => "Ihite", 'state_id' => 17),
            array('name' => "Nkwerre", 'state_id' => 17),
            array('name' => "Oguta", 'state_id' => 17),
            array('name' => "Okigwe", 'state_id' => 17),
            array('name' => "Owerri", 'state_id' => 17),
            array('name' => "Babura", 'state_id' => 18),
            array('name' => "Birnin Kudu", 'state_id' => 18),
            array('name' => "Buji", 'state_id' => 18),
            array('name' => "Dutse", 'state_id' => 18),
            array('name' => "Garki", 'state_id' => 18),
            array('name' => "Gumel", 'state_id' => 18),
            array('name' => "Gwaram", 'state_id' => 18),
            array('name' => "Gwiwa", 'state_id' => 18),
            array('name' => "Hadejia", 'state_id' => 18),
            array('name' => "Jahun", 'state_id' => 18),
            array('name' => "Kaugama", 'state_id' => 18),
            array('name' => "Kazaure", 'state_id' => 18),
            array('name' => "Keffin Hausa", 'state_id' => 18),
            array('name' => "Kiyawa", 'state_id' => 18),
            array('name' => "Maigatari", 'state_id' => 18),
            array('name' => "Malammaduri", 'state_id' => 18),
            array('name' => "Ringim", 'state_id' => 18),
            array('name' => "Sule Tankarkar", 'state_id' => 18),
            array('name' => "Taura", 'state_id' => 18),
            array('name' => "Birnin Gwari", 'state_id' => 19),
            array('name' => "Doka", 'state_id' => 19),
            array('name' => "Giwa", 'state_id' => 19),
            array('name' => "Gwagwada", 'state_id' => 19),
            array('name' => "Hunkuyi", 'state_id' => 19),
            array('name' => "Igabi", 'state_id' => 19),
            array('name' => "Ikara", 'state_id' => 19),
            array('name' => "Jemaa", 'state_id' => 19),
            array('name' => "Kachia", 'state_id' => 19),
            array('name' => "Kaduna", 'state_id' => 19),
            array('name' => "Kafanchan", 'state_id' => 19),
            array('name' => "Kagarko", 'state_id' => 19),
            array('name' => "Kagoro", 'state_id' => 19),
            array('name' => "Kaura", 'state_id' => 19),
            array('name' => "Kudan", 'state_id' => 19),
            array('name' => "Lere", 'state_id' => 19),
            array('name' => "Makarfi", 'state_id' => 19),
            array('name' => "Sabon Birnin Gwari", 'state_id' => 19),
            array('name' => "Sabongari", 'state_id' => 19),
            array('name' => "Sanga", 'state_id' => 19),
            array('name' => "Soba", 'state_id' => 19),
            array('name' => "Tudun Wada", 'state_id' => 19),
            array('name' => "Zangon Katab", 'state_id' => 19),
            array('name' => "Zaria", 'state_id' => 19),
            array('name' => "Ajingi", 'state_id' => 20),
            array('name' => "Albasu", 'state_id' => 20),
            array('name' => "Bagwai", 'state_id' => 20),
            array('name' => "Bebeji", 'state_id' => 20),
            array('name' => "Bichi", 'state_id' => 20),
            array('name' => "Bunkure", 'state_id' => 20),
            array('name' => "Dambarta", 'state_id' => 20),
            array('name' => "Dawakin Tofe", 'state_id' => 20),
            array('name' => "Fagge", 'state_id' => 20),
            array('name' => "Garko", 'state_id' => 20),
            array('name' => "Garun Mallam", 'state_id' => 20),
            array('name' => "Gaya", 'state_id' => 20),
            array('name' => "Gezawa", 'state_id' => 20),
            array('name' => "Gwarzo", 'state_id' => 20),
            array('name' => "Kabo", 'state_id' => 20),
            array('name' => "Kano", 'state_id' => 20),
            array('name' => "Karaye", 'state_id' => 20),
            array('name' => "Kibiya", 'state_id' => 20),
            array('name' => "Kiru", 'state_id' => 20),
            array('name' => "Kumbotso", 'state_id' => 20),
            array('name' => "Kunchi", 'state_id' => 20),
            array('name' => "Kura", 'state_id' => 20),
            array('name' => "Madobi", 'state_id' => 20),
            array('name' => "Makoda", 'state_id' => 20),
            array('name' => "Nassarawa", 'state_id' => 20),
            array('name' => "Rano", 'state_id' => 20),
            array('name' => "Rimin Gado", 'state_id' => 20),
            array('name' => "Shanono", 'state_id' => 20),
            array('name' => "Sumaila", 'state_id' => 20),
            array('name' => "Takai", 'state_id' => 20),
            array('name' => "Tofa", 'state_id' => 20),
            array('name' => "Tudun Wada", 'state_id' => 20),
            array('name' => "Wudil", 'state_id' => 20),
            array('name' => "Bakori", 'state_id' => 21),
            array('name' => "Batsari", 'state_id' => 21),
            array('name' => "Bindawa", 'state_id' => 21),
            array('name' => "Cheranchi", 'state_id' => 21),
            array('name' => "Dan Dume", 'state_id' => 21),
            array('name' => "Danja", 'state_id' => 21),
            array('name' => "Daura", 'state_id' => 21),
            array('name' => "Dutsi", 'state_id' => 21),
            array('name' => "Dutsin Ma", 'state_id' => 21),
            array('name' => "Faskari", 'state_id' => 21),
            array('name' => "Funtua", 'state_id' => 21),
            array('name' => "Ingawa", 'state_id' => 21),
            array('name' => "Jibiya", 'state_id' => 21),
            array('name' => "Kangiwa", 'state_id' => 21),
            array('name' => "Kankara", 'state_id' => 21),
            array('name' => "Kankiya", 'state_id' => 21),
            array('name' => "Katsina", 'state_id' => 21),
            array('name' => "Kurfi", 'state_id' => 21),
            array('name' => "Malumfashi", 'state_id' => 21),
            array('name' => "Mani", 'state_id' => 21),
            array('name' => "Mashi", 'state_id' => 21),
            array('name' => "Musawa", 'state_id' => 21),
            array('name' => "Rimi", 'state_id' => 21),
            array('name' => "Sandamu", 'state_id' => 21),
            array('name' => "Zango", 'state_id' => 21),
            array('name' => "Argungu", 'state_id' => 22),
            array('name' => "Augie", 'state_id' => 22),
            array('name' => "Bagudo", 'state_id' => 22),
            array('name' => "Birnin Kebbi", 'state_id' => 22),
            array('name' => "Birnin Yauri", 'state_id' => 22),
            array('name' => "Bunza", 'state_id' => 22),
            array('name' => "Fakai", 'state_id' => 22),
            array('name' => "Gwandu", 'state_id' => 22),
            array('name' => "Jega", 'state_id' => 22),
            array('name' => "Kalgo", 'state_id' => 22),
            array('name' => "Koko", 'state_id' => 22),
            array('name' => "Maiyema", 'state_id' => 22),
            array('name' => "Sakaba", 'state_id' => 22),
            array('name' => "Shanga", 'state_id' => 22),
            array('name' => "Suru", 'state_id' => 22),
            array('name' => "Wasagu", 'state_id' => 22),
            array('name' => "Zuru", 'state_id' => 22),
            array('name' => "Ajaokuta", 'state_id' => 23),
            array('name' => "Ankpa", 'state_id' => 23),
            array('name' => "Dekina", 'state_id' => 23),
            array('name' => "Idah", 'state_id' => 23),
            array('name' => "Kabba", 'state_id' => 23),
            array('name' => "Koton-Karifi", 'state_id' => 23),
            array('name' => "Kuroro", 'state_id' => 23),
            array('name' => "Lokoja", 'state_id' => 23),
            array('name' => "Mopa", 'state_id' => 23),
            array('name' => "Ogaminana", 'state_id' => 23),
            array('name' => "Ogori", 'state_id' => 23),
            array('name' => "Okene", 'state_id' => 23),
            array('name' => "Ajasse", 'state_id' => 24),
            array('name' => "Ilorin", 'state_id' => 24),
            array('name' => "Jebba", 'state_id' => 24),
            array('name' => "Kaiama", 'state_id' => 24),
            array('name' => "Lafiagi", 'state_id' => 24),
            array('name' => "Offa", 'state_id' => 24),
            array('name' => "Pategi", 'state_id' => 24),
            array('name' => "Apapa", 'state_id' => 25),
            array('name' => "Badagri", 'state_id' => 25),
            array('name' => "Epe", 'state_id' => 25),
            array('name' => "Ibeju", 'state_id' => 25),
            array('name' => "Iganmi", 'state_id' => 25),
            array('name' => "Ikeja", 'state_id' => 25),
            array('name' => "Ikorodu", 'state_id' => 25),
            array('name' => "Lagos", 'state_id' => 25),
            array('name' => "Ojo", 'state_id' => 25),
            array('name' => "Surulere", 'state_id' => 25),
            array('name' => "Akwanga", 'state_id' => 26),
            array('name' => "Awe", 'state_id' => 26),
            array('name' => "Doma", 'state_id' => 26),
            array('name' => "Keana", 'state_id' => 26),
            array('name' => "Keffi", 'state_id' => 26),
            array('name' => "Lafia", 'state_id' => 26),
            array('name' => "Nassarawa", 'state_id' => 26),
            array('name' => "Obi", 'state_id' => 26),
            array('name' => "Toto", 'state_id' => 26),
            array('name' => "Wamba", 'state_id' => 26),
            array('name' => "Agale", 'state_id' => 27),
            array('name' => "Babana", 'state_id' => 27),
            array('name' => "Bida", 'state_id' => 27),
            array('name' => "Bosso", 'state_id' => 27),
            array('name' => "Chanchaga", 'state_id' => 27),
            array('name' => "Gbako", 'state_id' => 27),
            array('name' => "Kontagora", 'state_id' => 27),
            array('name' => "Lapai", 'state_id' => 27),
            array('name' => "Minna", 'state_id' => 27),
            array('name' => "Mokwa", 'state_id' => 27),
            array('name' => "New Bussa", 'state_id' => 27),
            array('name' => "Rijau", 'state_id' => 27),
            array('name' => "Shiroro", 'state_id' => 27),
            array('name' => "Suleja", 'state_id' => 27),
            array('name' => "Wushishi", 'state_id' => 27),
            array('name' => "Abeokuta", 'state_id' => 28),
            array('name' => "Ado Odo", 'state_id' => 28),
            array('name' => "Agbara", 'state_id' => 28),
            array('name' => "Aiyetoro", 'state_id' => 28),
            array('name' => "Ewekoro", 'state_id' => 28),
            array('name' => "Ifo", 'state_id' => 28),
            array('name' => "Ijebu Igbo", 'state_id' => 28),
            array('name' => "Ijebu Ode", 'state_id' => 28),
            array('name' => "Ikene", 'state_id' => 28),
            array('name' => "Ilaro", 'state_id' => 28),
            array('name' => "Ipokia", 'state_id' => 28),
            array('name' => "Odogbolu", 'state_id' => 28),
            array('name' => "Owode", 'state_id' => 28),
            array('name' => "Sango Ota", 'state_id' => 28),
            array('name' => "Shagamu", 'state_id' => 28),
            array('name' => "Akure", 'state_id' => 29),
            array('name' => "Idanre", 'state_id' => 29),
            array('name' => "Ikare", 'state_id' => 29),
            array('name' => "Irele", 'state_id' => 29),
            array('name' => "Odigbo", 'state_id' => 29),
            array('name' => "Oka", 'state_id' => 29),
            array('name' => "Okitipupa", 'state_id' => 29),
            array('name' => "Ondo", 'state_id' => 29),
            array('name' => "Owo", 'state_id' => 29),
            array('name' => "Apomu", 'state_id' => 30),
            array('name' => "Ede", 'state_id' => 30),
            array('name' => "Ejigbo", 'state_id' => 30),
            array('name' => "Erin-Oshogbo", 'state_id' => 30),
            array('name' => "Gbongan", 'state_id' => 30),
            array('name' => "Ife", 'state_id' => 30),
            array('name' => "Ifon Osun", 'state_id' => 30),
            array('name' => "Ijesha", 'state_id' => 30),
            array('name' => "Ikire", 'state_id' => 30),
            array('name' => "Ikirun", 'state_id' => 30),
            array('name' => "Ila", 'state_id' => 30),
            array('name' => "Ilesha", 'state_id' => 30),
            array('name' => "Ilobu", 'state_id' => 30),
            array('name' => "Inisa", 'state_id' => 30),
            array('name' => "Iwo", 'state_id' => 30),
            array('name' => "Modakeke", 'state_id' => 30),
            array('name' => "Oke-Mesi", 'state_id' => 30),
            array('name' => "Olorunda", 'state_id' => 30),
            array('name' => "Olupona", 'state_id' => 30),
            array('name' => "Ore", 'state_id' => 30),
            array('name' => "Orolu", 'state_id' => 30),
            array('name' => "Oshogbo", 'state_id' => 30),
            array('name' => "Oyan", 'state_id' => 30),
            array('name' => "Akinyele", 'state_id' => 31),
            array('name' => "Egbeda", 'state_id' => 31),
            array('name' => "Eruwa", 'state_id' => 31),
            array('name' => "Fiditi", 'state_id' => 31),
            array('name' => "Ibadan", 'state_id' => 31),
            array('name' => "Ibeto", 'state_id' => 31),
            array('name' => "Igbo Ora", 'state_id' => 31),
            array('name' => "Igboho", 'state_id' => 31),
            array('name' => "Iseyin", 'state_id' => 31),
            array('name' => "Kajola", 'state_id' => 31),
            array('name' => "Kishi", 'state_id' => 31),
            array('name' => "Lalupon", 'state_id' => 31),
            array('name' => "Ogbomosho", 'state_id' => 31),
            array('name' => "Ogo", 'state_id' => 31),
            array('name' => "Oke-Iho", 'state_id' => 31),
            array('name' => "Oyo", 'state_id' => 31),
            array('name' => "Shaki", 'state_id' => 31),
            array('name' => "Barakin", 'state_id' => 32),
            array('name' => "Bassa", 'state_id' => 32),
            array('name' => "Bokkos", 'state_id' => 32),
            array('name' => "Bukuru", 'state_id' => 32),
            array('name' => "Jos", 'state_id' => 32),
            array('name' => "Langtang", 'state_id' => 32),
            array('name' => "Pankshin", 'state_id' => 32),
            array('name' => "Riyom", 'state_id' => 32),
            array('name' => "Shendam", 'state_id' => 32),
            array('name' => "Vom", 'state_id' => 32),
            array('name' => "Wase", 'state_id' => 32),
            array('name' => "Abonnema", 'state_id' => 33),
            array('name' => "Abua", 'state_id' => 33),
            array('name' => "Ahoada", 'state_id' => 33),
            array('name' => "Bonny", 'state_id' => 33),
            array('name' => "Bugama", 'state_id' => 33),
            array('name' => "Degema", 'state_id' => 33),
            array('name' => "Egbema", 'state_id' => 33),
            array('name' => "Ogu", 'state_id' => 33),
            array('name' => "Okrika", 'state_id' => 33),
            array('name' => "Omoko", 'state_id' => 33),
            array('name' => "Opobo", 'state_id' => 33),
            array('name' => "Oyigbo", 'state_id' => 33),
            array('name' => "Port Harcourt", 'state_id' => 33),
            array('name' => "Binji", 'state_id' => 34),
            array('name' => "Bodinga", 'state_id' => 34),
            array('name' => "Dange", 'state_id' => 34),
            array('name' => "Gada", 'state_id' => 34),
            array('name' => "Goronyo", 'state_id' => 34),
            array('name' => "Gwadabawa", 'state_id' => 34),
            array('name' => "Illela", 'state_id' => 34),
            array('name' => "Kebbe", 'state_id' => 34),
            array('name' => "Kware", 'state_id' => 34),
            array('name' => "Rabah", 'state_id' => 34),
            array('name' => "Raka", 'state_id' => 34),
            array('name' => "Sabon Birni", 'state_id' => 34),
            array('name' => "Sokoto", 'state_id' => 34),
            array('name' => "Tambawel", 'state_id' => 34),
            array('name' => "Tureta", 'state_id' => 34),
            array('name' => "Wamako", 'state_id' => 34),
            array('name' => "Wurno", 'state_id' => 34),
            array('name' => "Bali", 'state_id' => 35),
            array('name' => "Gashaka", 'state_id' => 35),
            array('name' => "Gassol", 'state_id' => 35),
            array('name' => "Ibi", 'state_id' => 35),
            array('name' => "Jalingo", 'state_id' => 35),
            array('name' => "Lau", 'state_id' => 35),
            array('name' => "Takum", 'state_id' => 35),
            array('name' => "Wukari", 'state_id' => 35),
            array('name' => "Yorro", 'state_id' => 35),
            array('name' => "Damaturu", 'state_id' => 36),
            array('name' => "Fika", 'state_id' => 36),
            array('name' => "Gashua", 'state_id' => 36),
            array('name' => "Geidam", 'state_id' => 36),
            array('name' => "Gorgoram", 'state_id' => 36),
            array('name' => "Gujba", 'state_id' => 36),
            array('name' => "Gulani", 'state_id' => 36),
            array('name' => "Jakusko", 'state_id' => 36),
            array('name' => "Matsena", 'state_id' => 36),
            array('name' => "Nguru", 'state_id' => 36),
            array('name' => "Potiskum", 'state_id' => 36),
            array('name' => "Yusufari", 'state_id' => 36),
            array('name' => "Anka", 'state_id' => 37),
            array('name' => "Bungudu", 'state_id' => 37),
            array('name' => "Chafe", 'state_id' => 37),
            array('name' => "Gummi", 'state_id' => 37),
            array('name' => "Gusau", 'state_id' => 37),
            array('name' => "Isa", 'state_id' => 37),
            array('name' => "Kaura Namoda", 'state_id' => 37),
            array('name' => "Kiyawa", 'state_id' => 37),
            array('name' => "Maradun", 'state_id' => 37),
            array('name' => "Maru", 'state_id' => 37),
            array('name' => "Shinkafe", 'state_id' => 37),
            array('name' => "Talata Mafara", 'state_id' => 37),
            array('name' => "Zurmi", 'state_id' => 37),
        );
        DB::table('cities')->insert($cities);
    }
}
